name: Test AWS Connection

on:
  push:
    branches:
      - main  # Se ejecutará cuando hagas push a la rama "main"

jobs:
  test-aws:
    runs-on: ubuntu-latest

    steps:
      # 1. Chequear el código del repositorio (es requerido por Actions)
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Configurar AWS con tus credenciales
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # 3. Comando simple para verificar que la autenticación funciona
      - name: Verify AWS authentication
        run: |
          aws sts get-caller-identity
